filter:
  paths: [lib/*]

tools:
  php_analyzer: true
  php_code_coverage: true
  php_code_sniffer:
    config:
      standard: PSR2
  php_hhvm: true
  php_mess_detector: true
  php_pdepend: true
  php_sim: true
  sensiolabs_security_checker: true
