language: php

php:
  - 7.1
  - 7.0
  - 5.6

sudo: false

install: composer install --dev --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - composer quality

after_script: vendor/bin/coveralls -v
