language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3

install: composer install --dev --no-interaction

script: vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_script: vendor/bin/coveralls -v
