language: php

php:
  - 5.5
  - 5.4
  - 5.3

before_script: composer install --dev --no-interaction

script: vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-clover clover.xml

after_script: vendor/bin/coveralls -v
