language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3

sudo: false

install: composer install --dev --no-interaction

script:
  - vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-clover build/logs/clover.xml
  - vendor/bin/phpcs --standard=PSR2 lib/ tests/

after_script: vendor/bin/coveralls -v
